In [1]:
import numpy as np

In [8]:
L = 12
x = [10, 20, 5, 10, 30, 40,10, 20, 5, 10, 30, 40,50, 40, 7, 20, 40, 50]
theta = 0.2
normalize=True

In [9]:
x = np.asarray(x, dtype=float)

In [10]:
x

array([10., 20.,  5., 10., 30., 40., 10., 20.,  5., 10., 30., 40., 50.,
       40.,  7., 20., 40., 50.])

In [11]:
len(x)

18

In [12]:
weights = theta ** np.arange(L + 1)

In [13]:
weights

array([1.000e+00, 2.000e-01, 4.000e-02, 8.000e-03, 1.600e-03, 3.200e-04,
       6.400e-05, 1.280e-05, 2.560e-06, 5.120e-07, 1.024e-07, 2.048e-08,
       4.096e-09])

In [14]:
len(weights)

13

Convolution slides the weight kernel across x and, at each position, computes a sum of products. Let me show it explicitly with small numbers:

In [16]:
k = np.convolve(x, weights)

In [18]:
len(k)

30

In [19]:
p = k[: len(x)]

In [20]:
p

array([10.        , 22.        ,  9.4       , 11.88      , 32.376     ,
       46.4752    , 19.29504   , 23.859008  ,  9.7718016 , 11.95436032,
       32.39087206, 46.47817441, 59.29563488, 51.85912697, 17.37182538,
       23.47436507, 44.69487301, 58.93897458])

In [21]:
len(p)

18